setwd("~/data/mrna-structure/phylogeny/")
library(plyr)

data_gene_range = read.csv("~/data/mrna-structure/phylogeny/Scer_n7_Spar_gene_range.csv",head=TRUE)
data_cds_range_chr = read.table("~/data/mrna-structure/phylogeny/protein_coding_list_range_chr.csv",head=FALSE,sep = ",")
colnames(data_cds_range_chr) = c("gene","chr","start","end")
data_gene_range = merge(data_cds_range_chr,data_gene_range,by="gene")
data_out <- arrange(data_gene_range,data_gene_range$chr,data_gene_range$start)
data_out_1 = subset(data_out, data_out$proporation==1)
write.csv(data_out_1,file="~/data/mrna-structure/phylogeny/Scer_n7_Spar_distance_processed_pro_1.csv",row.names = FALSE)
